package dev.aleian.pockethid.action

/**
 * Low-level execution plan generated by [ActionResolver].
 * Represents concrete HID reports dispatched to the transport layer.
 */
sealed interface ActionExecutionPlan {

    /**
     * Dispatch a single keyboard key click with optional modifier mask.
     */
    data class KeyStroke(
        val keyCode: Byte,
        val modifiers: Byte = 0
    ) : ActionExecutionPlan

    /**
     * Dispatch a Consumer Control usage code (Media play/pause, volume, mute).
     */
    data class ConsumerKey(
        val usageCode: Int
    ) : ActionExecutionPlan

    /**
     * Dispatch a discrete mouse button click (Left, Right, Middle).
     */
    data class MouseButtonClick(
        val buttonMask: Byte
    ) : ActionExecutionPlan

    /**
     * Sequential execution of multiple plans with a configurable inter-step delay.
     */
    data class Sequence(
        val steps: List<ActionExecutionPlan>,
        val stepDelayMs: Long = 15L
    ) : ActionExecutionPlan

    /**
     * Dispatch a Gamepad digital button click.
     */
    data class GamepadButtonClick(
        val buttonMask: Int
    ) : ActionExecutionPlan

    /**
     * Dispatch a desktop Zoom action via modifier key + mouse wheel step.
     */
    data class ZoomWheel(
        val wheelDelta: Int,
        val modifier: Byte
    ) : ActionExecutionPlan

    /**
     * No-operation plan (e.g. for unmapped actions on a specific OS).
     */
    data object NoOp : ActionExecutionPlan
}
